export const getStoreProfile = () => ({
  storeName: 'Main Store - Delhi',
  storeId: 'STORE-0001',
  location: 'Sector 5, New Delhi, India - 110001',
  coordinates: { lat: 28.5244, lng: 77.0855 },
  storeSize: 'Large',
  storeType: 'General Store',
  operatingHours: {
    monday: '9:00 AM - 11:00 PM',
    tuesday: '9:00 AM - 11:00 PM',
    wednesday: '9:00 AM - 11:00 PM',
    thursday: '9:00 AM - 11:00 PM',
    friday: '9:00 AM - 11:00 PM',
    saturday: '8:00 AM - 12:00 AM',
    sunday: '8:00 AM - 12:00 AM',
  },
  contactInfo: {
    phone: '+91-11-XXXX-XXXX',
    email: 'store.delhi@meridian.com',
  },
  manager: {
    name: 'Rajesh Kumar',
    email: 'rajesh@meridian.com',
    phone: '+91-98765-XXXXX',
  },
  demographics: {
    ageDistribution: {
      '18-25': 15,
      '25-35': 35,
      '35-50': 30,
      '50+': 20,
    },
    incomeLevel: 'Medium to High',
    preferences: ['Price-sensitive', 'Quality-focused', 'Trend-followers', 'Premium buyers'],
  },
  performanceBaseline: {
    dailyAverageSales: 45250,
    peakSeasonSales: 67500,
    offSeasonSales: 32100,
  },
});

export const getProductCatalog = () => [
  {
    id: 'prod-1',
    name: 'Premium Sweets Pack',
    category: 'Sweets & Confectionery',
    subcategory: 'Traditional Sweets',
    priceRange: '₹150-₹250',
    seasonality: 'High in festivals',
    trendSensitivity: 0.85,
  },
  {
    id: 'prod-2',
    name: 'Decorative Items Set',
    category: 'Decorations',
    subcategory: 'Festival Decorations',
    priceRange: '₹200-₹500',
    seasonality: 'Peak during Diwali/Holi',
    trendSensitivity: 0.92,
  },
  {
    id: 'prod-3',
    name: 'Traditional Clothing',
    category: 'Apparel',
    subcategory: 'Ethnic Wear',
    priceRange: '₹300-₹800',
    seasonality: 'Moderate throughout year',
    trendSensitivity: 0.72,
  },
  {
    id: 'prod-4',
    name: 'Cold Drinks Bundle',
    category: 'Beverages',
    subcategory: 'Non-Alcoholic',
    priceRange: '₹50-₹150',
    seasonality: 'High in summer',
    trendSensitivity: 0.68,
  },
  {
    id: 'prod-5',
    name: 'Household Essentials',
    category: 'Household Items',
    subcategory: 'Daily Needs',
    priceRange: '₹100-₹400',
    seasonality: 'Stable year-round',
    trendSensitivity: 0.45,
  },
];

export const getRegionalSettings = () => ({
  language: 'English',
  availableLanguages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada'],
  currency: 'Indian Rupees (₹)',
  localBusinessPractices: {
    creditPaymentSupport: true,
    localDeliveryService: true,
    customCreditTerms: '30-60 days for B2B',
  },
  festivalPreferences: [
    'Diwali',
    'Holi',
    'Eid',
    'Christmas',
    'New Year',
    'Regional Festivals',
  ],
  regionalCompetitors: [
    'LocalMart - New Delhi',
    'Premium Stores Co - Delhi',
    'Neighborhood Retail Chain',
  ],
  localSuppliers: [
    { name: 'Sweet Distributors Ltd', reliabilityScore: 92, leadTime: '3-5 days' },
    { name: 'Premium Distributors Co', reliabilityScore: 88, leadTime: '4-6 days' },
    { name: 'Festival Goods Hub', reliabilityScore: 82, leadTime: '2-3 days' },
    { name: 'Textile Suppliers Inc', reliabilityScore: 78, leadTime: '5-7 days' },
  ],
});

export const getIntegrations = () => [
  {
    id: 'int-1',
    name: 'POS System',
    status: 'connected',
    provider: 'Internal',
    lastSync: '2 hours ago',
    syncFrequency: 'Every 30 minutes',
    dataPoints: 'Transactions, Inventory, Sales',
  },
  {
    id: 'int-2',
    name: 'Weather API',
    status: 'connected',
    provider: 'OpenWeatherMap',
    lastSync: '15 minutes ago',
    syncFrequency: 'Every 30 minutes',
    dataPoints: 'Temperature, Humidity, Precipitation',
  },
  {
    id: 'int-3',
    name: 'Social Media - Twitter',
    status: 'connected',
    provider: 'Twitter API v2',
    lastSync: '45 minutes ago',
    syncFrequency: 'Every hour',
    dataPoints: 'Trending topics, Sentiment',
  },
  {
    id: 'int-4',
    name: 'Social Media - Instagram',
    status: 'connected',
    provider: 'Instagram Graph API',
    lastSync: '1 hour ago',
    syncFrequency: 'Every 2 hours',
    dataPoints: 'Visual trends, User engagement',
  },
  {
    id: 'int-5',
    name: 'Economic Data',
    status: 'connected',
    provider: 'RBI',
    lastSync: '1 day ago',
    syncFrequency: 'Daily',
    dataPoints: 'Inflation indices, Economic indicators',
  },
  {
    id: 'int-6',
    name: 'Supplier API',
    status: 'disconnected',
    provider: 'Supplier Network',
    lastSync: 'N/A',
    syncFrequency: 'Not configured',
    dataPoints: 'Inventory, Pricing',
  },
];
