export const getDocuments = () => [
  {
    id: 'doc-1',
    type: 'Invoice',
    fileName: 'INV-2026-001.pdf',
    uploadDate: '2026-02-28',
    uploadTime: '10:30 AM',
    status: 'processed',
    validationResult: 'No anomalies',
    vendor: 'Sweet Distributors Ltd',
    anomalies: 0,
  },
  {
    id: 'doc-2',
    type: 'Shipment',
    fileName: 'SHIP-5678.jpg',
    uploadDate: '2026-02-27',
    uploadTime: '2:45 PM',
    status: 'processed',
    validationResult: '2 discrepancies',
    vendor: 'Premium Goods Co',
    anomalies: 2,
  },
  {
    id: 'doc-3',
    type: 'Invoice',
    fileName: 'INV-2026-002.pdf',
    uploadDate: '2026-02-26',
    uploadTime: '11:15 AM',
    status: 'approved',
    validationResult: 'No anomalies',
    vendor: 'Textile Suppliers Inc',
    anomalies: 0,
  },
  {
    id: 'doc-4',
    type: 'Shipment',
    fileName: 'SHIP-5679.pdf',
    uploadDate: '2026-02-25',
    uploadTime: '4:20 PM',
    status: 'flagged',
    validationResult: 'Requires review',
    vendor: 'Festival Goods Hub',
    anomalies: 3,
  },
];

export const getDetailedDocument = () => ({
  id: 'doc-2',
  type: 'Shipment',
  fileName: 'SHIP-5678.jpg',
  uploadDate: '2026-02-27',
  uploadTime: '2:45 PM',
  uploadedBy: 'John Retailer',
  preview: '/document-preview.jpg',
  extractedData: {
    shipmentId: 'SHIP-5678',
    origin: 'Premium Goods Warehouse, Mumbai',
    destination: 'Main Store - Delhi',
    vendor: 'Premium Goods Co',
    shippingDate: '2026-02-26',
    expectedDelivery: '2026-02-28',
    items: [
      { product: 'Decorative Items Set', orderedQty: 400, receivedQty: 395, unit: 'units' },
      { product: 'Traditional Clothing', orderedQty: 250, receivedQty: 250, unit: 'units' },
    ],
    totalItems: 2,
    totalQuantity: 645,
    carrier: 'Express Logistics',
    trackingNumber: 'TRACK-12345-67890',
  },
  validationStatus: {
    schemaValidation: { status: 'passed', message: 'All required fields present' },
    businessRules: { status: 'passed', message: 'All values within acceptable range' },
    poMatch: { status: 'warning', message: 'Quantity mismatch detected' },
  },
  anomalies: [
    {
      id: 'anom-1',
      severity: 'warning',
      title: 'Quantity Variance: Decorative Items Set',
      description: 'Ordered 400 units but received 395 units (5 unit shortage)',
      suggestedAction: 'Contact supplier for clarification or accept variance',
      relatedLineItem: 'Decorative Items Set',
    },
    {
      id: 'anom-2',
      severity: 'info',
      title: 'Price Variance',
      description: '2% higher than last order for same product',
      suggestedAction: 'Confirm with supplier if this is new pricing',
      relatedLineItem: 'Traditional Clothing',
    },
  ],
  anomaliesCount: 2,
  matchPercentage: 87,
  auditTrail: [
    {
      timestamp: '2026-02-27 14:45',
      actor: 'John Retailer',
      action: 'Uploaded document',
    },
    {
      timestamp: '2026-02-27 14:46',
      actor: 'System',
      action: 'Validation completed',
    },
    {
      timestamp: '2026-02-27 14:47',
      actor: 'System',
      action: 'Flagged for manual review',
    },
    {
      timestamp: '2026-02-27 14:50',
      actor: 'System',
      action: 'Status: Awaiting approval',
    },
  ],
});

export const getChatMessages = () => [
  {
    id: 'msg-1',
    type: 'user',
    content: 'What should I stock for Diwali?',
    timestamp: new Date(Date.now() - 5 * 60000),
  },
  {
    id: 'msg-2',
    type: 'assistant',
    content: 'Based on trends, here are my Diwali stocking recommendations:',
    timestamp: new Date(Date.now() - 4 * 60000),
    recommendations: [
      { product: 'Premium Sweets Pack', qty: 350, confidence: 92, risk: 'Low' },
      { product: 'Decorative Items Set', qty: 400, confidence: 87, risk: 'Medium' },
      { product: 'Traditional Clothing', qty: 250, confidence: 78, risk: 'High' },
    ],
  },
  {
    id: 'msg-3',
    type: 'user',
    content: 'Generate purchase order',
    timestamp: new Date(Date.now() - 3 * 60000),
  },
  {
    id: 'msg-4',
    type: 'assistant',
    content: 'I\'ve created a draft PO with the recommended quantities. Total cost: ₹243,625. Supplier: Sweet Distributors Ltd (92% reliability).',
    timestamp: new Date(Date.now() - 2 * 60000),
    poId: 'PO-2026-0001',
    poDetails: {
      items: 3,
      cost: 243625,
      supplier: 'Sweet Distributors Ltd',
      status: 'draft',
    },
  },
];

export const getSuggestedQueries = () => [
  'What should I stock for Diwali?',
  'Show me demand forecast for next week',
  'Generate purchase order for category X',
  'Analyze recent trends',
  'Which products underperformed?',
  'How did sales perform during Holi?',
  'What\'s trending in my market?',
  'Optimize my shelf space',
];
