export const getPurchaseOrders = () => [
  {
    id: 'PO-2026-0001',
    createdDate: '2026-02-28',
    dueDate: '2026-03-05',
    supplier: 'Sweet Distributors Ltd',
    supplierReliability: 92,
    store: 'Main Store - Delhi',
    totalItems: 3,
    estimatedCost: 207500,
    status: 'draft',
    leadTime: '3-5 days',
  },
  {
    id: 'PO-2026-0002',
    createdDate: '2026-02-27',
    dueDate: '2026-03-02',
    supplier: 'Premium Goods Co',
    supplierReliability: 85,
    store: 'Main Store - Delhi',
    totalItems: 2,
    estimatedCost: 95000,
    status: 'pending-approval',
    leadTime: '2-3 days',
  },
  {
    id: 'PO-2026-0003',
    createdDate: '2026-02-26',
    dueDate: '2026-03-01',
    supplier: 'Textile Suppliers Inc',
    supplierReliability: 78,
    store: 'Main Store - Delhi',
    totalItems: 1,
    estimatedCost: 75000,
    status: 'approved',
    leadTime: '2 days',
  },
];

export const getDetailedPO = () => ({
  id: 'PO-2026-0001',
  dateCreated: '2026-02-28',
  dueDate: '2026-03-05',
  supplier: {
    name: 'Sweet Distributors Ltd',
    contact: 'contact@sweetdist.com',
    phone: '+91-11-XXXX-XXXX',
    reliability: 92,
    leadTime: '3-5 days',
    capacity: 'High',
    address: 'Sector 5, Noida, UP',
  },
  store: {
    name: 'Main Store - Delhi',
    location: 'Delhi',
    contact: 'store.delhi@meridian.com',
  },
  items: [
    {
      product: 'Premium Sweets Pack',
      recommendedQty: 350,
      orderedQty: 350,
      unitPrice: 150,
      totalCost: 52500,
      leadTime: '2 days',
      notes: 'Standard assortment',
    },
    {
      product: 'Decorative Items Set',
      recommendedQty: 400,
      orderedQty: 400,
      unitPrice: 200,
      totalCost: 80000,
      leadTime: '4 days',
      notes: 'Festival special pack',
    },
    {
      product: 'Traditional Clothing',
      recommendedQty: 250,
      orderedQty: 250,
      unitPrice: 300,
      totalCost: 75000,
      leadTime: '3 days',
      notes: 'Assorted sizes',
    },
  ],
  costSummary: {
    productCost: 207500,
    delivery: 5000,
    tax: 31125,
    total: 243625,
  },
  budgetImpact: {
    monthlyBudget: 500000,
    usedSoFar: 210000,
    thisOrder: 243625,
    totalAfter: 453625,
    percentUsed: 90.7,
    remaining: 46375,
  },
  alternativeSuppliers: [
    {
      name: 'Premium Distributors Co',
      leadTime: '4-6 days',
      cost: 235000,
      savings: 8625,
      reliability: 88,
    },
    {
      name: 'Festival Goods Hub',
      leadTime: '2-3 days',
      cost: 255000,
      savings: -11375,
      reliability: 82,
    },
  ],
  deliverySchedule: {
    expectedDeliveryDate: '2026-03-05',
    warehouseAvailability: 'Available',
    canSplitShipment: true,
  },
  recommendationReason: 'Diwali festival demand spike detected with 92% confidence',
  confidenceScore: 92,
  internalNotes: '',
  approvalHistory: [],
});

export const getSupplierComparison = () => [
  {
    name: 'Sweet Distributors Ltd',
    cost: 243625,
    leadTime: '3-5 days',
    reliability: 92,
    isSelected: true,
  },
  {
    name: 'Premium Distributors Co',
    cost: 235000,
    leadTime: '4-6 days',
    reliability: 88,
    isSelected: false,
  },
  {
    name: 'Festival Goods Hub',
    cost: 255000,
    leadTime: '2-3 days',
    reliability: 82,
    isSelected: false,
  },
];
